### ISSUE TITLE
Broken Stickers: after adding a new sticker pack, I can't use stickers anymore

### ISSUE THREAD

**Issue by franzcor** [vector-im/element-integration-manager#1]
### Steps to reproduce

I added a new stickerpack from the selection menu and, after confirming the operation, I can't use the stickers anymore.
I get a "Missing access token" when I click on the stickers panel.
A friend of mine had the same issue on element android with a fresh account.

![immagine](https://user-images.githubusercontent.com/78822766/176311860-abe58f40-a676-4679-b994-ee8501b0cae7.png)

### Outcome

I'd expect to be able to send stickers

#### What happened instead?

The stickers popup is broken and doesn't allow me to send them.

### Operating system

Debian testing

### Browser information

Firefox esr

### URL for webapp

app.element.io

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by nWacky** [comment]
That worked for me

**Comment by franzcor** [comment]
@AndrewFerr While it works for me, trying to make it work from element web, it doesn't work for a friend of mine who tried from element on android and never used element on web.
