### ISSUE TITLE
Sticker picker doesn't work for some users

### ISSUE THREAD

**Issue by JasonGitly** [vector-im/element-integration-manager#11]
When I log in as the main user (that is the only admin) I can use the stickers, but when I log in as any other user, I get this error on Android devices whenever I try to access the sticker widget. In the Windows desktop app, nothing happens (I see the same log in the console as mentioned here: https://github.com/vector-im/riot-web/issues/6853 )

![riot-403](https://user-images.githubusercontent.com/41263669/42733967-f3ad6200-882a-11e8-976a-a77431c19ede.png)

**Comment by Half-Shot** [comment]
I believe this is probably federation issues, but the time has long since passed.
