### ISSUE TITLE
Modular UX: "Add to room" for bots is add odds with "Save" button of widgets

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-integration-manager#25]
There should be a more uniform interface for the concept of "Adding an integration to a room".  It would make sense for part of the UI to include a "+" that allows the user to add an _instance_ of an integration to a room, whether that's a bridge link, bot or widget.

This would probably fall out of refactoring the entire thing so that each integration isn't using it's own special react component (although in practice this is probably unlikely to be possible).

**Comment by Half-Shot** [comment]
New UI, closing.
