### ISSUE TITLE
The RSS bot name should not include the name of the user who added the bot

### ISSUE THREAD

**Issue by MarkWieczorek** [vector-im/element-integration-manager#32]
#### What would you like to do?
Whenever the RSS bot posts something, the bot's user name is listed as `RSS Bot [@some-random-user:matrix.org]`. In my opinion, there is no reason to include the user name of the person who created the bot in the name of the bot.

#### Why would you like to do it?
When creating an RSS bot for use in a public room, it is very distracting and annoying to keep seeing `RSS Bot [@some-random-user:matrix.org]` with every post. Why should I care who created the bot?

#### How would you like to achieve it?
Name the RSS bot `RSS bot` instead of `RSS Bot [@some-random-user:matrix.org]`

**Comment by Half-Shot** [comment]
This is no longer a concern with the new bot.
