### ISSUE TITLE
Add a profile image for the RSS bot, instead of using the default "R" in a cirlce.

### ISSUE THREAD

**Issue by MarkWieczorek** [vector-im/element-integration-manager#33]
#### What would you like to do?
The RSS bot does not have an image in its profile. As a result, the image associated with every RSS bot post is the default "R" in a circle. I would like the RSS bot to have a nice image associated with it.

#### Why would you like to do it?
One thing that keeps users away from Matrix/Element is that the interface is, lets just say, not pretty. We should strive to make the interface look good.

#### How would you like to achieve it?
I would simply add an icon to the profile of the RSS bot. The default "RSS icon" would probably be fine, but I am sure that someone could come up with something better if they really wanted to.

**Comment by Half-Shot** [comment]
Fixed in the new bot.
