### ISSUE TITLE
gitter.im: cannot remove integration

### ISSUE THREAD

**Issue by virtuald** [vector-im/element-integration-manager#34]
### Steps to reproduce

1. Add an integration
2. Go back to integrations
3. ... no option to remove an integration?

#### What did you expect?

If I can add it, surely I can remove it.

#### What happened instead?

Confusion.

### Will you send logs?

No

**Comment by Half-Shot** [comment]
We've since moved onto a new integration manager, so this may or may not affect you still. Please open if it does.
