### ISSUE TITLE
API Error (403): Missing access token

### ISSUE THREAD

**Issue by Biep** [vector-im/element-integration-manager#37]
**Describe the bug**
I migrated to a new laptop (Ubuntu 22.04).  I can run Element Desktop there with no problems, but when I try to open an integration (Etherpad or Ethercalc), I get this error instead: "API Error (403): Missing access token".  Clearing the cache does not help.

**To Reproduce**
No idea whether, and under what conditions, this is reproducible.  Here is roughly what I did:
1. Back up my old laptop
2. Install the backed-up `/home` on the new laptop
3. Install Element Desktop using `apt`
4. Run Element.
5. Try to open an integration.
6. Consent to the warning that the integration is not as safe as the room.

**Expected behavior**
The integration ought to have opened.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/12461597/224029203-c52ab1dd-4eab-44ea-a620-23742e4bc4fe.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 (both on the old and the new laptop)
 - Browser Element Desktop
 - Version 1.11.24

**Comment by Half-Shot** [comment]
I think this is no longer the case with the new appstore, but let us know if it is.

**Comment by Biep** [comment]
I still have the issue on 1.11.25.  Will it be gone on 1.11.26?
Not sure what you mean by "app store" - I installed the standard repository version.

**Comment by Biep** [comment]
I am on 1.11.39 now, and the issue is still there.  Please help!
