### ISSUE TITLE
Error occured during widget load: The operation is insecure

### ISSUE THREAD

**Issue by msrd0** [vector-im/element-integration-manager#46]
**Describe the bug**

I just got a notification that the old Github integration is deprecated and I should update. Adding the new Github integration results in the following error message, which prevents any configuration:

![image](https://user-images.githubusercontent.com/7853372/227061237-4b769686-7a89-491e-844a-f69eaa7a6ee4.png)

**To Reproduce**
1. Go to a room
2. Add new Github integration

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser: Firefox Developer Edition
 - Version: 112.0b5-1

**Comment by Half-Shot** [comment]
Hiya, having looked into this, it appears to be the Firefox privacy settings causing this one:

![image](https://user-images.githubusercontent.com/2072976/227151897-dc4f0961-50f7-4119-94f7-319ddbd44a7c.png)

If you set the privacy setting to anything more lax than "Cookies from unvisited web sites" then this should work, but Firefox seems to be blocking cookies from websites you haven't directly visited. The integration manager works by loading in an iframe of the bridge's configuration widget, so it's entirely possible that it's paranoid about that.

The Strict setting should also work. In the meantime, we will look into how to make it less paranoid.

**Comment by msrd0** [comment]
These are my settings, and they're staying that way. I hope you can find a way to make the integration work with these settings.

![Screenshot_2023-03-23-10-43-41](https://user-images.githubusercontent.com/7853372/227164166-8dfdfe40-c98c-4645-ae4e-c5d9f2b7acf6.png)

**Comment by Half-Shot** [comment]
Right, solution coming up in https://github.com/matrix-org/matrix-hookshot/issues/677. The use of local storage in this case is an optimisation, but we can work around it.

**Comment by Half-Shot** [comment]
Workaround was deployed.
