### ISSUE TITLE
Github-Bot Migration: Instructions not clear - does not work? 

### ISSUE THREAD

**Issue by mtippmann** [vector-im/element-integration-manager#47]
Started the migration according to the [docs](https://ems-docs.element.io/books/element-cloud-documentation/page/migrate-to-the-new-github-and-feeds-bots) - I'm admin in the room  and added the original github bot with my matrix account. After migration I authenticated again with github and gave the integration permissions for the wohle project... but there are no new events and I'm not sure if there is still something to do for finishing the migration or if the state in the screenshots is enough? 

my github account is linked with the 'weimarnetz' project and permissions from the github side are granted: 
![image](https://user-images.githubusercontent.com/187041/227065790-170a1efb-cee0-4275-baab-a8b352e71fc1.png)

this is the screen for the migrated repos - is there something missing here? 
![image](https://user-images.githubusercontent.com/187041/227065835-43f7db92-6805-4ba9-a3f4-ec7bdf7f9105.png)

**Comment by mtippmann** [comment]
using Element Desktop 

Version von Element: 1.11.20
Version von Olm: 3.2.12

**Comment by Half-Shot** [comment]
Hey there, would you mind giving us a room & userID so we can follow up in the logs? I'm afraid knowing the GitHub info isn't enough.

**Comment by tobbi** [comment]
I'm not OP but having the same problem:
Room: !BfYVBjzEVacHrvDBYw:matrix.org

Whose user ID do you need? Mine, if so, that'd be @tobbi:matrix.org

**Comment by mtippmann** [comment]
> Hey there, would you mind giving us a room & userID so we can follow up in the logs? I'm afraid knowing the GitHub info isn't enough.

sure room is `!SWQlgopOguLKBpcADp:bau-ha.us` alias `#weimarnetz:bau-ha.us` 
userid is `mt@bau-ha.us` 

thanks for looking into it

**Comment by jplatte** [comment]
Yeah, this seems badly broken.

- To migrate multiple repos, I had to assign multiple `!foo` prefixes, but not doing it did not result in any UI feedback
- Clicking any of the checkboxes for which events should generate notifications does nothing, both before and after migration

**Comment by tobbi** [comment]
From my end, it looks like it was fixed.

**Comment by mtippmann** [comment]
I removed the bot in the meanwhile and comments here and tickets suggest it's fixed. So I'm closing this issue.
