### ISSUE TITLE
Can't migrate GitHub connections

### ISSUE THREAD

**Issue by neilalexander** [vector-im/element-integration-manager#50]
**Describe the bug**

In the integration manager for `#yggdrasil:matrix.org`, there's a "Migrate connections" section but apparently no actionable item to complete the migration. 

Is there supposed to be a "Submit" button?

**Screenshots**

<img width="1063" alt="Screenshot 2023-03-23 at 09 54 36" src="https://user-images.githubusercontent.com/310854/227167364-8ac11ae6-bd7f-479d-a2b8-2abfe4da5af8.png">

<img width="1060" alt="Screenshot 2023-03-23 at 09 54 43" src="https://user-images.githubusercontent.com/310854/227167378-d4e3bdfc-02bd-45c2-bdca-d5739fb506cf.png">

**Desktop (please complete the following information):**

Element Desktop version 1.11.25
macOS 13.2.1 (22D68)

**Comment by Half-Shot** [comment]
There should be a submit button https://github.com/matrix-org/matrix-hookshot/blob/main/web/components/roomConfig/GithubRepoConfig.tsx#L155, so it's not happy with one of these state items.
