### ISSUE TITLE
[Feeds] Make it possible to see the URL to the feed you added

### ISSUE THREAD

**Issue by natrius** [vector-im/element-integration-manager#52]
**Is your feature request related to a problem? Please describe.**
The problem is, after adding a feed there is no URL visible anymore. Its not possible to give someone else a link or add a new feed with some little change. 
A workaround is adding the URL to the description of the URL like i did
![image](https://user-images.githubusercontent.com/7243447/227460761-c191630a-8a27-4dfe-9d4e-c0657d597778.png)

**Describe the solution you'd like**
When opening the description of the Feed, add a line with the URL

**Comment by Half-Shot** [comment]
Sounds sensible, I think we lost these when we added label support. Tracked upstream in https://github.com/matrix-org/matrix-hookshot/issues/679.
