### ISSUE TITLE
Device not supported but I am on element web

### ISSUE THREAD

**Issue by erdnaxeli** [vector-im/element-integration-manager#53]
**Describe the bug**
When opening the integration manager on element web, it tells me my device isn't supported.

**Expected behavior**
It works.

**Screenshots**
![image](https://user-images.githubusercontent.com/479441/227479093-c8c5f835-898c-4ae0-8481-c6de8d645860.png)

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Browser: Firefox
 - Version: 111

**Additional context**
I am using my own HS on cervoi.se.

**Comment by Half-Shot** [comment]
Very strange, I think we basically try to do some API calls that should work on EWeb, and if those fail we show this. I'll take a look.

**Comment by erdnaxeli** [comment]
I see no error in the network inspector.

**Comment by Half-Shot** [comment]
Had a look at this, looks like the user was on an ancient version of Element. The minimum we support there is https://github.com/vector-im/element-web/releases/tag/v1.11.18 due to requiring ability to read events.
