### ISSUE TITLE
Cannot add any feeds with the new bot

### ISSUE THREAD

**Issue by drgibbon** [vector-im/element-integration-manager#59]
**Describe the bug**
I can't add any feeds to the new RSS bot, on the [Slackware room](https://matrix.to/#/#slackware:matrix.org).

**To Reproduce**
Steps to reproduce the behaviour:
1. `Room Info` -> `Add widgets, bridges & bots` -> `Feeds` 
2. Add `https://mirrors.slackware.com/feeds/slackware64-15.0.rss` to URL.
3. Add `Slackware64 15.0` to Label.
4. Error message: "Failed to create connection: Unknown error"

**Expected behaviour**
The feed would be added.

**Client**
Element version: 1.11.25 (running in browser)
Tested Vivaldi 5.6.2867.50 and Firefox ESR 102.9.0

**Comment by drgibbon** [comment]
Still not working for me I'm afraid, room ID `!txOpDzDRbZXoMPztLz:matrix.org`

**Comment by drgibbon** [comment]
Updated my Element client to `1.11.26`, now I get a decent error message when trying to add a feed:
> error Failed to create connection: Bot has a PL of 50 but needs at least 100.

Is that for real, it wants admin power? 🤔

**Comment by Twi1ightSparkle** [comment]
Feeds needs permissions to edit room state (`state_default`) as this is where it stores your config. By default, this is Moderator (power level 50). Check `Roles & Permissions` ->  `Change settings` in the settings for your room.

**Comment by drgibbon** [comment]
Right, but the bot currently has Moderator power, and the error message when adding a feed is:
> error Failed to create connection: Bot has a PL of 50 but needs at least 100.

Why would it be asking for PL of 100?

**Comment by drgibbon** [comment]
@Twi1ightSparkle I'm wondering if under `Roles & Permissions` and `Permissions` there's some specific permission that it needs? I couldn't find one called `state_default` though.

**Comment by Twi1ightSparkle** [comment]
> @Twi1ightSparkle I'm wondering if under `Roles & Permissions` and `Permissions` there's some specific permission that it needs? I couldn't find one called `state_default` though.

`state_default` = `Change settings` in Element room permission settings

**Comment by drgibbon** [comment]
Excellent thanks very much, our room's `Change settings` was set to `Admin`. I returned it to `Default` and the feed bot is working properly.

**Comment by Twi1ightSparkle** [comment]
`Default` means any room members can set room state, you very likely don't want that. The default settings for `Change settings` is Moderator

**Comment by drgibbon** [comment]
Oops, OK, I assumed "Default" meant the server default..
