### ISSUE TITLE
Github bot not sending comments

### ISSUE THREAD

**Issue by razzeee** [vector-im/element-integration-manager#60]
**Is your feature request related to a problem? Please describe.**
The old bot did allow to show comments in matrix

**Describe the solution you'd like**
I would like the new bot to also be able to show the comments

**Describe alternatives you've considered**
Not showing comments I guess?

**Additional context**
Migration from the old github bot to the new one

**Comment by Half-Shot** [comment]
Comments on...GitHub issues or PRs?

**Comment by razzeee** [comment]
Ideally both, at least I can't choose them here

![image](https://user-images.githubusercontent.com/5943908/227945167-e6b0e26f-03e0-4049-af47-4ba77b626bf5.png)

**Comment by mosra** [comment]
Would it be possible to include also pushes/commits in the events? Currently I work around that with RSS feeds, but it'd be great to have everything handled by a single bot. Thank you! :)

**Comment by Half-Shot** [comment]
> Would it be possible to include also pushes/commits in the events? Currently I work around that with RSS feeds, but it'd be great to have everything handled by a single bot. Thank you! :)

This will land in https://github.com/matrix-org/matrix-hookshot/pull/696

**Comment by stephanedupont** [comment]
> Would it be possible to include also pushes/commits in the events? Currently I work around that with RSS feeds, but it'd be great to have everything handled by a single bot. Thank you! :)

+1, the old integration was publishing commits, the new one doesn't. It would be great if we could get that feature back!

**Comment by Half-Shot** [comment]
This has since landed and should be accessible from the integration config tab.

**Comment by razzeee** [comment]
Did you only land comments on issues or on PRs too? Cause I'm not sure I'm seeing the latter one.
