### ISSUE TITLE
Feeds bot: Failed to create connection: Could not read feed from URL

### ISSUE THREAD

**Issue by MarkWieczorek** [vector-im/element-integration-manager#62]
**Describe the bug**
Adding a feed to a room gives the error

```
Failed to create connection: Could not read feed from URL: Request failed with status code 403
```
**To Reproduce**
1. Go to a room that already has the new rss feed bot.
2. Try to add "https://www.lpi.usra.edu/planetary_news/feed/"

room: !GeZUmZzjfKIeFnffoJ:matrix.org

**Expected behavior**
I have migrated about 100 RSS feeds the last week. I have had multiple problems and errors, but this is the first time I ran into this error.

**Screenshots**

**Client (please complete the following information):**
 - Matrix Client and Version: Element-web

**Comment by Twi1ightSparkle** [comment]
Looks like https://github.com/matrix-org/matrix-hookshot/issues/548

**Comment by MarkWieczorek** [comment]
1. On my system, `curl -I 'https://www.lpi.usra.edu/planetary_news/feed/'` does not return any errors. I get
```
HTTP/2 403
date: Wed, 29 Mar 2023 13:09:20 GMT
content-type: text/html; charset=UTF-8
cache-control: max-age=15
expires: Wed, 29 Mar 2023 13:09:35 GMT
x-frame-options: SAMEORIGIN
server: cloudflare
cf-ray: 7af858c59e4ddd23-LHR
```
2. This feed works fine with the Slack RSS bot.
