### ISSUE TITLE
RSS bot configurable hiding temporary timeouts

### ISSUE THREAD

**Issue by mahdi1234** [vector-im/element-integration-manager#63]
**Is your feature request related to a problem? Please describe.**

Legacy RSS bot did not spam about feed being temporarily down. New bot fills room with messages as below which I could redact, but would stay forever on bridged protocols like IRC (screen is taken from IRC room using matterbridge)

![hide_errors](https://user-images.githubusercontent.com/1097047/228532609-b775acbf-4c23-438f-93db-708c81ef0f01.png)

**Describe the solution you'd like**
Configure whether to see those or not. For me it's good enough validate feed existence when adding it.

**Describe alternatives you've considered**
DM with room admins/mods or given users for these messages.

**Comment by Half-Shot** [comment]
I think we'll just add an option to hide errors, it's been a widely requested one :).

**Comment by vranki** [comment]
Suggestion: Just disable error reporting until this has been implemented.

Currently the bot spams errors to rooms randomly when there are some network hiccups and that is annoying users.

**Comment by Half-Shot** [comment]
N.B. An update to fix this will be out shortly.
