### ISSUE TITLE
Feed migration either isn't shown or `error Failed to fetch existing connections: Unknown error`

### ISSUE THREAD

**Issue by Mikaela** [vector-im/element-integration-manager#65]
**Describe the bug**

I cannot migrate feeds from the old bot. I hit either two issues:

- no feeds appear.
- I wait a long time to receive error: `error Failed to fetch existing connections: Unknown error`

**To Reproduce**

1. Go to room with old bot (`@_neb_rssbot_=40_ciblia=3amatrix.org:matrix.org`)
2. Open integration manager
3. Select feeds.

**Expected behavior**

I expected to see a list of feeds that I can migrate to Hookshot. Instead in one room I am just asked to add new feeds and another one throws me a `error Failed to fetch existing connections: Unknown error`

**Screenshots**

Not that applicable.

**Client (please complete the following information):**
 - Matrix Client and Version: Element-versio: 89054a50acb2-react-6f791d28c84a-js-d1cf98b1770d
Olm-versio: 3.2.12
 - Matrix Client Version: Element-versio: 89054a50acb2-react-6f791d28c84a-js-d1cf98b1770d
Olm-versio: 3.2.12
 - Browser: Brave
 - Browser Version: Versio 1.52.5 Chromium: 112.0.5615.49 (Virallinen koontiversio) nightly (64-bittinen)

**Additional context**

I have a legacy MXID with a capital letter (`@Ciblia:matrix.org`), maybe Hookshot cannot handle those? I cannot attempt with another account due to https://github.com/vector-im/element-integration-manager/issues/57.

**Comment by Twi1ightSparkle** [comment]
The [fix](https://github.com/matrix-org/matrix-hookshot/pull/695) for https://github.com/vector-im/element-integration-manager/issues/57 should be deployed next week. Hopefully this will resolve your issue and allow you to migrate your feeds.

**Comment by Mikaela** [comment]
Resolved by https://github.com/matrix-org/matrix-hookshot/pull/695
