### ISSUE TITLE
[Feeds] Code 500/503/timeout after migrating from old RSS-Integration

### ISSUE THREAD

**Issue by depressivum** [vector-im/element-integration-manager#66]
**Describe the bug**
Former working feeds not working after migration following this article:
https://ems-docs.element.io/books/element-cloud-documentation/page/migrate-to-the-new-github-and-feeds-bots

**To Reproduce**
Follow 
https://ems-docs.element.io/books/element-cloud-documentation/page/migrate-to-the-new-github-and-feeds-bots
and migrate to the new Feeds bot
Wait for the next feed update

**Expected behavior**
Getting RSS-Feed instead of error 500/503/timeout

**Screenshots**
![feeds](https://user-images.githubusercontent.com/26390366/229203485-5f315361-18ef-4d30-8812-9f8141a72301.png)
![image](https://user-images.githubusercontent.com/26390366/229204647-4ccdf4f5-e92a-47de-98e1-e70420ae160a.png)

**Client (please complete the following information):**

**Comment by mahdi1234** [comment]
Seems to be same as #63 ?

**Comment by depressivum** [comment]
Duplicate of https://github.com/vector-im/element-integration-manager/issues/63
