### ISSUE TITLE
Can't edit/delete migrated feed

### ISSUE THREAD

**Issue by razzeee** [vector-im/element-integration-manager#71]
**Describe the bug**
I have a room `!SvPtrbYMvQtrCpiJKX:matrix.org` which has had feeds configured and I've migrated it to the new one. It shows the migrated settings, but I can't edit or remove it.

I only want to remove it, as it seems to not work and not post any new items.

**To Reproduce**
1. Go to Extensions > Feeds
2. Find your migrated feed
3. Try to update or delete it
4. See error message

**Expected behavior**
It should allow me to delete/unsubscribe or edit it

**Screenshots**
![image](https://user-images.githubusercontent.com/5943908/230875532-678c502b-08a4-49eb-ab4c-eb59ddf4506b.png)

![image](https://user-images.githubusercontent.com/5943908/230875581-da6deca6-02d7-47aa-86a3-e5ba5601f59c.png)

**Client (please complete the following information):**
 - Matrix Client and Version: Element Web
 - Browser Firefox

**Comment by Half-Shot** [comment]
Looks like https://github.com/matrix-org/matrix-hookshot/issues/707. The bot doesn't think it's in the room, so it can't remove the connection. Can you confirm if the bot is removed (and/or has moderator powers) in order to remove the connection?

**Comment by razzeee** [comment]
![image](https://user-images.githubusercontent.com/5943908/231131756-d85bb3c5-b2e3-49d5-b05b-3e15c8df3428.png)

This is at least what the sidepanel says

**Comment by Half-Shot** [comment]
Would you mind giving it a kick and reinviting it?

**Comment by razzeee** [comment]
I have `uninvited` it and re-invited it via the integration manager. But it doesn't seem to join and is still not allowing me to unsubscribe (unsurprisingly)

**Comment by Half-Shot** [comment]
Right, so coming back to this it looks like integrations.ems.host and matrix.org had diverged and were confused about who was joined where. I have left and rejoined the room, so I think if you give it moderator permissions to unset the room state, you should be good to go.

**Comment by razzeee** [comment]
I'm now able to change these, so I guess we can close. I'll see if the RSS actually posts now. Not sure when we will update that particular feed.
