### ISSUE TITLE
Scalar integs that try to open new windows fail on Electron

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-integration-manager#88]
Some Scalar integs (eg. Slack bridging) try to `window.open` to do OAuth. This is slightly broken in the Electron app because we intercept `window.open` and open the URL in the user's browser. You can still auth, and if you make the integration try again, it will work, but the you get a message telling you to enable popups and you have to manually get it to re-poll.

**Comment by Half-Shot** [comment]
Believe the Slack widget thing was entirely my fault and the only place we ever did this. We no longer use the scalar-web widgets so this can be closed.
