### ISSUE TITLE
Travis CI integration does not appear to work

### ISSUE THREAD

**Issue by neilalexander** [vector-im/element-integration-manager#9]
### Description

Travis CI integration through the "Manage Integrations" section in Riot does not appear to work.

### Steps to reproduce

- Enable integration. The bot joins the room. (Channel affected is `#seaglass:matrix.org`)
- Copy the relevant section into `.travis.yml` and trigger a CI build.
- No notifications are produced in the channel on builds.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Safari
- **OS**: macOS
- **URL**: riot.im/app

**Comment by Half-Shot** [comment]
We've dropped travis.
