### ISSUE TITLE
Google docs widget doesn't update title when the document title changes

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-integration-manager#91]
### Description

![image](https://user-images.githubusercontent.com/1190097/35872414-03159322-0b24-11e8-99ea-66c70130bafb.png)

Yes, I know it's hard to do this. Instead, it might be worth specifically setting the `title` on the widget to be something else. The title does update when changing rooms though (provided the URL previewer doesn't cache the result).

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by Half-Shot** [comment]
We no longer have a gdocs widget.
