### ISSUE TITLE
Bridge Riot---Slack: not all Riot messages are posted to Slack

### ISSUE THREAD

**Issue by maudnals** [vector-im/element-integration-manager#94]
### Description

Slack bridge: not all messages posted from Riot are visible in Slack. For the **same user** posting from Riot, their messages are sometimes visible in Slack and sometimes not.
I would expect their messages to always be visible in Slack.

### Steps to reproduce

- Create a new Riot room
- Create a new Slack channel 
- Bridge them using the Events API
- For User X posting from Riot, their messages are sometimes visible in Slack and sometimes not. 

Logs being sent: no

### Version information

- **Platform**: web + desktop

Riot web:
- **Browser**: Chrome
- **OS**: macOS
- **URL**: https://riot.im/app/#/room/#kilt-general:matrix.org

Slack desktop: macOS, version 4.0.1

**Comment by Half-Shot** [comment]
I think this has probably rotted.
