### ISSUE TITLE
riot.im/develop should use scalar-live, not scalar-staging (and integ mgrs should be selectable)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-integration-manager#95]
Currently riot-develop is hardcoded in the config to use scalar-staging. This means any widgets provisioned by riot-develop users end up on scalar’s staging platform for the rest of their lives, as the platform’s url is baked into the widget state event.

Given integs are a bit of a poweruser feature, this means a disproportionate amount of them are provisioned by powerusers on riot-develop, meaning that scalar-staging ends up being much more operationally important than we might think.

We saw this first hand when recovering from the security breach, where problems on staging had disproportionate impact.

I suggest that riot-develop is moved to use scalar-staging by default, but we change config.json to support multiple integ mgr entries. the user can then switch between them in UserSettings if they consciously want to use a different manager for testing or variety etc.

Similarly, we really need a way to tell which widgets come from which integ manager (and which integ manager web UI you are using!) - whether that’s colourscheme, beta icons or whatever, so that we can flush out all the spurious old staging widgets which have ended up being provisioned everywhere.

@rxl881 thoughts?

**Comment by Half-Shot** [comment]
This isn't hardcoded anymore?
